class MoviesController < ApplicationController
  def index
    page = params[:page] || 1

    response = HTTP.auth("Bearer #{ENV["MOVIE_ACCESS_TOKEN"]}").get("https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=#{page}&sort_by=popularity.desc&with_genres=%2C")
    movie_data = response.parse(:json)
    movies = movie_data["results"]

    genre_response = HTTP.auth("Bearer #{ENV["MOVIE_ACCESS_TOKEN"]}").get("https://api.themoviedb.org/3/genre/movie/list?language=en")
    genre_data = genre_response.parse(:json)
    genres = genre_data["genres"]

    movies_with_genres = movies.map do |movie|
      genre_names = genres.select { |genre| movie["genre_ids"].include?(genre["id"]) }.map { |genre| genre["name"] }
      movie.merge("genres" => genre_names)
    end

    render json: movies_with_genres
  end
end

# FAKE INDEX ACTION SO I CANT SCARE MYSELF WHILE WORKING ON FAVORITES

# class MoviesController < ApplicationController
#   def index
#     page = params[:page] || 1

#     movies = [
#       {
#         "adult": false,
#         "backdrop_path": "/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg",
#         "genre_ids": [
#           878,
#           12,
#           28,
#         ],
#         "id": 447365,
#         "original_language": "en",
#         "original_title": "Guardians of the Galaxy Vol. 3",
#         "overview": "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
#         "popularity": 4435.867,
#         "poster_path": "/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
#         "release_date": "2023-05-03",
#         "title": "Guardians of the Galaxy Vol. 3",
#         "video": false,
#         "vote_average": 8.1,
#         "vote_count": 2945,
#         "genres": [
#           "Action",
#           "Adventure",
#           "Science Fiction",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/woJbg7ZqidhpvqFGGMRhWQNoxwa.jpg",
#         "genre_ids": [
#           28,
#           12,
#           878,
#         ],
#         "id": 667538,
#         "original_language": "en",
#         "original_title": "Transformers: Rise of the Beasts",
#         "overview": "When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.",
#         "popularity": 5409.104,
#         "poster_path": "/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
#         "release_date": "2023-06-06",
#         "title": "Transformers: Rise of the Beasts",
#         "video": false,
#         "vote_average": 7.3,
#         "vote_count": 989,
#         "genres": [
#           "Action",
#           "Adventure",
#           "Science Fiction",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
#         "genre_ids": [
#           28,
#           80,
#           53,
#         ],
#         "id": 385687,
#         "original_language": "en",
#         "original_title": "Fast X",
#         "overview": "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
#         "popularity": 2027.836,
#         "poster_path": "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
#         "release_date": "2023-05-17",
#         "title": "Fast X",
#         "video": false,
#         "vote_average": 7.4,
#         "vote_count": 2667,
#         "genres": [
#           "Action",
#           "Crime",
#           "Thriller",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/oqP1qEZccq5AD9TVTIaO6IGUj7o.jpg",
#         "genre_ids": [
#           14,
#           28,
#           12,
#         ],
#         "id": 455476,
#         "original_language": "en",
#         "original_title": "Knights of the Zodiac",
#         "overview": "When a headstrong street orphan, Seiya, in search of his abducted sister unwittingly taps into hidden powers, he discovers he might be the only person alive who can protect a reincarnated goddess, sent to watch over humanity. Can he let his past go and embrace his destiny to become a Knight of the Zodiac?",
#         "popularity": 1882.774,
#         "poster_path": "/tBiUXvCqz34GDeuY7jK14QQdtat.jpg",
#         "release_date": "2023-04-27",
#         "title": "Knights of the Zodiac",
#         "video": false,
#         "vote_average": 6.5,
#         "vote_count": 464,
#         "genres": [
#           "Action",
#           "Adventure",
#           "Fantasy",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/rPBeEi1tU8IhQ9rbdnlLU0d0NR.jpg",
#         "genre_ids": [
#           28,
#           12,
#           18,
#         ],
#         "id": 445651,
#         "original_language": "en",
#         "original_title": "The Darkest Minds",
#         "overview": "After a disease kills 98% of America's children, the surviving 2% develop superpowers and are placed in internment camps. A 16-year-old girl escapes her camp and joins a group of other teens on the run from the government.",
#         "popularity": 1113.4,
#         "poster_path": "/94RaS52zmsqaiAe1TG20pdbJCZr.jpg",
#         "release_date": "2018-07-25",
#         "title": "The Darkest Minds",
#         "video": false,
#         "vote_average": 7,
#         "vote_count": 2482,
#         "genres": [
#           "Action",
#           "Adventure",
#           "Drama",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/eMPxmNvJjxVZIQWI2t1VmNC5IuR.jpg",
#         "genre_ids": [
#           28,
#           18,
#         ],
#         "id": 678512,
#         "original_language": "en",
#         "original_title": "Sound of Freedom",
#         "overview": "The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.",
#         "popularity": 1579.562,
#         "poster_path": "/mx4O9OEvIB265VM3UATLslsSW5t.jpg",
#         "release_date": "2023-07-03",
#         "title": "Sound of Freedom",
#         "video": false,
#         "vote_average": 8.3,
#         "vote_count": 69,
#         "genres": [
#           "Action",
#           "Drama",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/zcySy6dnSmyqiichtDgO7AEeZoq.jpg",
#         "genre_ids": [
#           28,
#           18,
#           53,
#         ],
#         "id": 254128,
#         "original_language": "en",
#         "original_title": "San Andreas",
#         "overview": "In the aftermath of a massive earthquake in California, a rescue-chopper pilot makes a dangerous journey across the state in order to rescue his estranged daughter.",
#         "popularity": 1398.565,
#         "poster_path": "/2Gfjn962aaFSD6eST6QU3oLDZTo.jpg",
#         "release_date": "2015-05-27",
#         "title": "San Andreas",
#         "video": false,
#         "vote_average": 6.2,
#         "vote_count": 7795,
#         "genres": [
#           "Action",
#           "Drama",
#           "Thriller",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
#         "genre_ids": [
#           28,
#           12,
#           16,
#           878,
#         ],
#         "id": 569094,
#         "original_language": "en",
#         "original_title": "Spider-Man: Across the Spider-Verse",
#         "overview": "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
#         "popularity": 1219.174,
#         "poster_path": "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
#         "release_date": "2023-05-31",
#         "title": "Spider-Man: Across the Spider-Verse",
#         "video": false,
#         "vote_average": 8.5,
#         "vote_count": 2210,
#         "genres": [
#           "Action",
#           "Adventure",
#           "Animation",
#           "Science Fiction",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/7I6VUdPj6tQECNHdviJkUHD2u89.jpg",
#         "genre_ids": [
#           28,
#           53,
#           80,
#         ],
#         "id": 603692,
#         "original_language": "en",
#         "original_title": "John Wick: Chapter 4",
#         "overview": "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
#         "popularity": 1076.994,
#         "poster_path": "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
#         "release_date": "2023-03-22",
#         "title": "John Wick: Chapter 4",
#         "video": false,
#         "vote_average": 7.9,
#         "vote_count": 3648,
#         "genres": [
#           "Action",
#           "Crime",
#           "Thriller",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/PwI3EfasE9fVuXsmMu9ffJh0Re.jpg",
#         "genre_ids": [
#           27,
#           9648,
#           53,
#         ],
#         "id": 406563,
#         "original_language": "en",
#         "original_title": "Insidious: The Last Key",
#         "overview": "Parapsychologist Elise Rainier and her team travel to Five Keys, NM, to investigate a man’s claim of a haunting. Terror soon strikes when Rainier realizes that the house he lives in was her family’s old home.",
#         "popularity": 994.525,
#         "poster_path": "/nb9fc9INMg8kQ8L7sE7XTNsZnUX.jpg",
#         "release_date": "2018-01-03",
#         "title": "Insidious: The Last Key",
#         "video": false,
#         "vote_average": 6.3,
#         "vote_count": 2520,
#         "genres": [
#           "Horror",
#           "Mystery",
#           "Thriller",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/euO884625eFLfKLoc0MtFs5QiOS.jpg",
#         "genre_ids": [
#           9648,
#           53,
#           28,
#         ],
#         "id": 1070802,
#         "original_language": "en",
#         "original_title": "Confidential Informant",
#         "overview": "During a crack epidemic two narcotics agents hunting for a cop killer. Hoping for leads, Moran and Thorton pay off a junkie informant. To provide for his wife and son, Moran involves the stool pigeon in a deadly scheme. This causes the partners to come under the scrutiny of a suspicious internal affairs agent.",
#         "popularity": 785.791,
#         "poster_path": "/qyU7H6OIvojQW0pjgjZjyNCP343.jpg",
#         "release_date": "2023-06-27",
#         "title": "Confidential Informant",
#         "video": false,
#         "vote_average": 6.1,
#         "vote_count": 47,
#         "genres": [
#           "Action",
#           "Mystery",
#           "Thriller",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/qe0oK0A5ovrlgH39Ga13dxxw9MU.jpg",
#         "genre_ids": [
#           28,
#           35,
#           80,
#         ],
#         "id": 1130818,
#         "original_language": "en",
#         "original_title": "Sheroes",
#         "overview": "When four thick-as-thieves friends arrive in Thailand they quickly find themselves in over their heads. Fighting to stay alive they employ their unique set of skills and unleash their fierce loyalty in a heart-pumping battle for survival.",
#         "popularity": 1008.07,
#         "poster_path": "/itUAkQmihFmRxMYTa3AkvIzMCV4.jpg",
#         "release_date": "2023-06-23",
#         "title": "Sheroes",
#         "video": false,
#         "vote_average": 5.6,
#         "vote_count": 42,
#         "genres": [
#           "Action",
#           "Comedy",
#           "Crime",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg",
#         "genre_ids": [
#           16,
#           10751,
#           12,
#           14,
#           35,
#         ],
#         "id": 502356,
#         "original_language": "en",
#         "original_title": "The Super Mario Bros. Movie",
#         "overview": "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.",
#         "popularity": 1091.431,
#         "poster_path": "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
#         "release_date": "2023-04-05",
#         "title": "The Super Mario Bros. Movie",
#         "video": false,
#         "vote_average": 7.8,
#         "vote_count": 5591,
#         "genres": [
#           "Adventure",
#           "Animation",
#           "Comedy",
#           "Family",
#           "Fantasy",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/nHf61UzkfFno5X1ofIhugCPus2R.jpg",
#         "genre_ids": [
#           35,
#           12,
#           14,
#         ],
#         "id": 346698,
#         "original_language": "en",
#         "original_title": "Barbie",
#         "overview": "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
#         "popularity": 1001.318,
#         "poster_path": "/cgYg04miVQUAG2FKk3amSnnHzOp.jpg",
#         "release_date": "2023-07-19",
#         "title": "Barbie",
#         "video": false,
#         "vote_average": 8.6,
#         "vote_count": 23,
#         "genres": [
#           "Adventure",
#           "Comedy",
#           "Fantasy",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/cSYLX73WskxCgvpN3MtRkYUSj1T.jpg",
#         "genre_ids": [
#           16,
#           35,
#           10751,
#           14,
#           10749,
#         ],
#         "id": 976573,
#         "original_language": "en",
#         "original_title": "Elemental",
#         "overview": "In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.",
#         "popularity": 959.617,
#         "poster_path": "/8riWcADI1ekEiBguVB9vkilhiQm.jpg",
#         "release_date": "2023-06-14",
#         "title": "Elemental",
#         "video": false,
#         "vote_average": 7.5,
#         "vote_count": 442,
#         "genres": [
#           "Animation",
#           "Comedy",
#           "Family",
#           "Fantasy",
#           "Romance",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/628Dep6AxEtDxjZoGP78TsOxYbK.jpg",
#         "genre_ids": [
#           28,
#           12,
#           53,
#         ],
#         "id": 575264,
#         "original_language": "en",
#         "original_title": "Mission: Impossible - Dead Reckoning Part One",
#         "overview": "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the world's fate at stake and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan must consider that nothing can matter more than his mission—not even the lives of those he cares about most.",
#         "popularity": 894.111,
#         "poster_path": "/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
#         "release_date": "2023-07-08",
#         "title": "Mission: Impossible - Dead Reckoning Part One",
#         "video": false,
#         "vote_average": 8.1,
#         "vote_count": 212,
#         "genres": [
#           "Action",
#           "Adventure",
#           "Thriller",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/mV1HOCbUqx7nfFPwledYsvMYHrw.jpg",
#         "genre_ids": [
#           28,
#           53,
#         ],
#         "id": 47964,
#         "original_language": "en",
#         "original_title": "A Good Day to Die Hard",
#         "overview": "Iconoclastic, take-no-prisoners cop John McClane, finds himself for the first time on foreign soil after traveling to Moscow to help his wayward son Jack - unaware that Jack is really a highly-trained CIA operative out to stop a nuclear weapons heist. With the Russian underworld in pursuit, and battling a countdown to war, the two McClanes discover that their opposing methods make them unstoppable heroes.",
#         "popularity": 841.291,
#         "poster_path": "/evxtv4e8Amm436Y5rW16RkGu8pX.jpg",
#         "release_date": "2013-02-06",
#         "title": "A Good Day to Die Hard",
#         "video": false,
#         "vote_average": 5.3,
#         "vote_count": 5931,
#         "genres": [
#           "Action",
#           "Thriller",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/qi6Edc1OPcyENecGtz8TF0DUr9e.jpg",
#         "genre_ids": [
#           27,
#           9648,
#           53,
#         ],
#         "id": 423108,
#         "original_language": "en",
#         "original_title": "The Conjuring: The Devil Made Me Do It",
#         "overview": "Paranormal investigators Ed and Lorraine Warren encounter what would become one of the most sensational cases from their files. The fight for the soul of a young boy takes them beyond anything they'd ever seen before, to mark the first time in U.S. history that a murder suspect would claim demonic possession as a defense.",
#         "popularity": 769.776,
#         "poster_path": "/xbSuFiJbbBWCkyCCKIMfuDCA4yV.jpg",
#         "release_date": "2021-05-25",
#         "title": "The Conjuring: The Devil Made Me Do It",
#         "video": false,
#         "vote_average": 7.5,
#         "vote_count": 5205,
#         "genres": [
#           "Horror",
#           "Mystery",
#           "Thriller",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/hPcP1kv6vrkRmQO3YgV1H97FE5Q.jpg",
#         "genre_ids": [
#           27,
#           9648,
#           53,
#         ],
#         "id": 614479,
#         "original_language": "en",
#         "original_title": "Insidious: The Red Door",
#         "overview": "To put their demons to rest once and for all, Josh Lambert and a college-aged Dalton Lambert must go deeper into The Further than ever before, facing their family's dark past and a host of new and more horrifying terrors that lurk behind the red door.",
#         "popularity": 745.271,
#         "poster_path": "/uS1AIL7I1Ycgs8PTfqUeN6jYNsQ.jpg",
#         "release_date": "2023-07-05",
#         "title": "Insidious: The Red Door",
#         "video": false,
#         "vote_average": 5.9,
#         "vote_count": 147,
#         "genres": [
#           "Horror",
#           "Mystery",
#           "Thriller",
#         ],
#       },
#       {
#         "adult": false,
#         "backdrop_path": "/zxnfMi4qW0bdAtcwCogrR9dRrqd.jpg",
#         "genre_ids": [
#           878,
#           9648,
#           53,
#         ],
#         "id": 1103825,
#         "original_language": "en",
#         "original_title": "War of the Worlds: The Attack",
#         "overview": "Three young astronomers fight to survive a deadly Martian invasion.",
#         "popularity": 760.902,
#         "poster_path": "/c3CUKHtQUvPvp9NSFsKwYsPLAdW.jpg",
#         "release_date": "2023-04-21",
#         "title": "War of the Worlds: The Attack",
#         "video": false,
#         "vote_average": 6,
#         "vote_count": 24,
#         "genres": [
#           "Mystery",
#           "Science Fiction",
#           "Thriller",
#         ],
#       },
#     ]

#     movies_with_genres = movies.map do |movie|
#       movie.merge("genres" => movie["genres"])
#     end

#     render json: movies_with_genres
#   end
# end
